### ISSUE TITLE
Question on coverage

### ISSUE THREAD

**Issue by kuraga** [3cp/browser-do#10]
Good day!

How do I turn on coverage support?

Can I do it without `--tap`?

Thanks.

**Comment by 3cp** [comment]
The coverage json file is only written (if `window.__coverage__` is available) when you run a tape/jasmine/mocha test.

What's your use case?

**Comment by kuraga** [comment]
Arbitary code.

Well I don't see any coverage output even with `--tap` and `window.__coverage__ = { foo: 'bar' };` in JavaScript file...

BTW seems like stderr isn't shown without `--tap`...

**Comment by 3cp** [comment]
The file is generated when browser-do detects test (TAP format output) is finished.

If your input file has some full tap output, it will exist and write the json file correctly.

Otherwise, you need to ctrl-c to kill browser-do, it doesn't do the coverage thing.

For example, I use a test input like this:
```js
window.__coverage__ = { 'foo' : 'bar' };
[                 
    'TAP version 13',
    '# wait',
    'ok 1 (unnamed assert)',
    'ok 2 should be equal',
    '1..2',
    '# tests 2',
    '# pass  2'
  ].forEach(l => console.log(l));
```

```bash
huocp@Chunpengs-MacBook-Pro ~/g/browser-do (master)> cat | ./bin/browser-do.js --tap
window.__coverage__ = { 'foo' : 'bar' };
[                 
    'TAP version 13',
    '# wait',
    'ok 1 (unnamed assert)',
    'ok 2 should be equal',
    '1..2',
    '# tests 2',
    '# pass  2'
  ].forEach(l => console.log(l));
TAP version 13
# wait
ok 1 (unnamed assert)
ok 2 should be equal
1..2
# tests 2
# pass  2
# code coverage is written to .nyc_output/out.json
# you can use "npx nyc report --reporter=lcov --reporter=text"
# then view coverage/lcov-report/index.html in a browser
```

**Comment by 3cp** [comment]
I got no problem to pass through stdout and stderr without using --tap.

```bash
huocp@Chunpengs-MacBook-Pro ~/g/browser-do (master)> cat | ./bin/browser-do.js
console.log("normal log");
console.error("error log");
normal log
error log
```

Note when you redirect the output to a file, it only redirects stdout. You need to use:
```bash
browser-do < input-file.js > stdout.txt 2> stderr.txt
```
Or
```bash
browser-do < input-file.js > out_and_err.txt > 2>&1
```

**Comment by kuraga** [comment]
Well, propose to generate coverage info without `--tap`.

**Comment by kuraga** [comment]
Yes, it was incorrect that stderr is not shown.

But one more: on exception, nothing happens. Nor exception info is shown, nor exit. Is it correct?

**Comment by 3cp** [comment]
> Well, propose to generate coverage info without `--tap`.

Unfortunately, it's not that simple.

By nature of JavaScript, browser-do cannot determine when it's the time to stop. For example, JS can use setTimeout, setInterval to run logic indefinitely. In fact, all test frameworks run unit tests in delayed fashion.

Browser-do stops only in two occations:
1) tap mode detects the end of tests.
2) JS explicitly called `window.close()` to close browser window.

It's possible to hijack `window.close()` to finalise coverage. But there is another catch. The coverage data is pushed from client side to server side (browser-do) in websocket, means it's async. But `window.close()` is a sync operation, user expects nothing happens after it's called. I don't think I can change the behaviour of `window.close()` to async as it will surprise and confuse user.

What you can do is to print out a minimum TAP output when it's time to gather coverage data.

Following is sufficient.
```js
console.log("1..1\nok\n");
```

**Comment by 3cp** [comment]
Exception printing is fine for me. Provide an example of your problem pls.

```bash
huocp@Chunpengs-MacBook-Pro ~/g/browser-do (master) [1]> node bin/browser-do.js
throw new Error("Hello");
Error: Hello
    at http://localhost:49442/bundle.js:1:7
```

As the same reason in previous post. Exception is not a reason to close browser window and exit. JavaScript can throw as much as exception it wants.

Can JS throw exception and keep running? Of cause it can.
```js
setInterval(() => {throw new Error("test")}, 1000)
```

browser-do only bridges stdout and stderr to terminal, it doesn't dictate the behaviour of input JavaScript. There are only two ways to exist browser-do naturally as shown above.

The other unnatural way to exit is using Ctrl-C to kill browser-do (which will kill child processes: the server and browser).

**Comment by kuraga** [comment]
Oh, I think now "stderr" and "exception" issues were [tman](https://github.com/thunks/tman) + [rollup](https://rollupjs.org/) + [browser-do](https://github.com/3cp/browser-do) issues. And I couldn't reproduce them in simple tests. Maybe, they're asynchronious issues. (Exactly: without `--tap` it didn't execute a finish callback with `console.log('Tests finished: ...')`; but with `--tap` did.)

Sorry for this!

**Comment by kuraga** [comment]
> But there is another catch.

Ok, thanks!

**Comment by 3cp** [comment]
Your missed exception printing might be some delayed print after TAP is finished.
You can use `-k` to keep browser-do running after TAP is finished, to see if that error comes out.

**Comment by kuraga** [comment]
No, there were both: nor exception, nor exit.

**Comment by 3cp** [comment]
Set both `-b chrome -k`, you can go to the real browser console to see what is going on.

**Comment by 3cp** [comment]
BTW, it looks like you can write a TAP reporter for tman.
